#pragma once
/**
 * @file bitwig_icons_14.hpp
 * @brief LVGL binary font data for Bitwig icons (14px, 4bpp)
 * Auto-generated by generate_lvgl_binary_font.sh
 */

#include <Arduino.h>

extern const uint8_t bitwig_icons_14_bin[] PROGMEM;
extern const uint32_t bitwig_icons_14_bin_len;
