"""
Bitwig SysEx Messages - Entry Point

This module serves as the entry point for message definitions.
All messages are organized by category in the message/ subdirectory
and are automatically discovered and loaded.

ARCHITECTURE
------------
- Message categories: message/transport.py, message/parameter.py, etc.
- Auto-discovery: All .py files in message/ are automatically imported
- Auto-registration: Messages use setMessage(registry=ALL_MESSAGES)
- Protocol package: Generic tools (Field, Flow, Type) from installed package

ADDING NEW MESSAGES
-------------------
1. Create or edit a category file (e.g., message/transport.py)
2. Define messages using setMessage() with registry=ALL_MESSAGES
3. The message is automatically discovered and included in generation

CATEGORIES
----------
Currently implemented:
- transport: Transport control (play, record, tempo feedback)

Planned:
- parameter: Parameter control (values, names, touch)
- device: Device management (select, info, banks)
- track: Track control (select, volume, mute, solo)
- system: System messages (ping, handshake, version)

MESSAGE STRUCTURE
-----------------
Each message has:
- flow: Message direction (Flow.CONTROLLER_TO_HOST | HOST_TO_CONTROLLER | BIDIRECTIONAL)
- description: Human-readable description
- fields: List of Field() objects referencing atomic types from types.yaml

FIELD COMPOSITION
-----------------
Fields reference atomic types from types.yaml or builtin_types.yaml:
- Simple field: Field('play', Type.UINT8)
- Atomic type: Field('param', Type.PARAMETERVALUE)
- Array: Field('params', Type.PARAMETERVALUE, array=8)

SYSEX ID ALLOCATION
-------------------
Message IDs are auto-generated by Flow direction:
- Controller → Host: 0x00-0x3F (64 slots)
- Host → Controller: 0x40-0xBF (128 slots)
- Bidirectional: 0xC0-0xC7 (8 slots)
"""

# Import ALL_MESSAGES from local message/ directory (auto-discovery already executed)
from .message import ALL_MESSAGES  # noqa: F401 - Exported for protocol generator

# That's it! ALL_MESSAGES is populated with messages from all categories.
# The protocol generator imports this file and uses ALL_MESSAGES for code generation.

# Export ALL_MESSAGES for external use
__all__ = ['ALL_MESSAGES']
