#!/bin/bash
#
# Bitwig Icon Font Generator for LVGL
# Generates binary font data from SVG icons for embedded use
#
# Usage: ./tools/font/generate_lvgl_binary_font.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FONT_DIR="$PROJECT_ROOT/src/ui/font"
DATA_DIR="$FONT_DIR/data"
TTF_FILE="$SCRIPT_DIR/bitwig_icons.ttf"
BIN_FILE="$SCRIPT_DIR/bitwig_icons_14.bin"

# Font settings
FONT_SIZE=14
BPP=4
FONT_NAME="bitwig_icons_14"
ARRAY_NAME="${FONT_NAME}_bin"

log() { echo -e "${BLUE}●${NC} $1"; }
success() { echo -e "  ${GREEN}✓${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1" >&2; exit 1; }

# -----------------------------------------------------------------------------
# Step 1: Generate TTF + header (Python)
# -----------------------------------------------------------------------------
log "Generating TTF from SVG icons..."

cd "$PROJECT_ROOT"
RANGE=$(uv run python tools/font/generate_icon_font.py)

if [[ -z "$RANGE" ]]; then
    error "Failed to get unicode range from Python script"
fi

if [[ ! -f "$TTF_FILE" ]]; then
    error "TTF file not generated: $TTF_FILE"
fi

success "TTF generated (range: $RANGE)"

# -----------------------------------------------------------------------------
# Step 2: Convert TTF to LVGL binary
# -----------------------------------------------------------------------------
log "Converting to LVGL binary (${FONT_SIZE}px, ${BPP}bpp)..."

if ! command -v lv_font_conv &> /dev/null; then
    error "lv_font_conv not found. Install with: npm install -g lv_font_conv"
fi

lv_font_conv \
    --font "$TTF_FILE" \
    --size "$FONT_SIZE" \
    --format bin \
    --bpp "$BPP" \
    --range "$RANGE" \
    --no-kerning \
    -o "$BIN_FILE"

if [[ ! -f "$BIN_FILE" ]]; then
    error "Binary file not generated"
fi

BIN_SIZE=$(stat -c%s "$BIN_FILE" 2>/dev/null || stat -f%z "$BIN_FILE" 2>/dev/null)
success "Binary generated ($BIN_SIZE bytes)"

# -----------------------------------------------------------------------------
# Step 3: Convert to C array
# -----------------------------------------------------------------------------
log "Generating C array..."

mkdir -p "$DATA_DIR"

C_INC_FILE="$DATA_DIR/${FONT_NAME}.c.inc"
HPP_FILE="$DATA_DIR/${FONT_NAME}.hpp"

# Generate C array with xxd
xxd -i "$BIN_FILE" > "$C_INC_FILE"

# Fix variable names (xxd uses full path)
sed -i "s/unsigned char [^=]*=/const uint8_t ${ARRAY_NAME}[] PROGMEM =/g" "$C_INC_FILE"
sed -i "s/unsigned int [^;]*;/const uint32_t ${ARRAY_NAME}_len = $BIN_SIZE;/g" "$C_INC_FILE"

success "$(basename "$C_INC_FILE")"

# Generate header
cat > "$HPP_FILE" << EOF
#pragma once
/**
 * @file ${FONT_NAME}.hpp
 * @brief LVGL binary font data for Bitwig icons (${FONT_SIZE}px, ${BPP}bpp)
 * Auto-generated by generate_lvgl_binary_font.sh
 */

#include <Arduino.h>

extern const uint8_t ${ARRAY_NAME}[] PROGMEM;
extern const uint32_t ${ARRAY_NAME}_len;
EOF

success "$(basename "$HPP_FILE")"

# -----------------------------------------------------------------------------
# Step 4: Cleanup
# -----------------------------------------------------------------------------
log "Cleaning up..."
rm -f "$TTF_FILE" "$BIN_FILE"
success "Temporary files removed"

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
echo ""
echo -e "${GREEN}✓ Icon font generated successfully${NC}"
echo ""
echo "Files:"
echo "  src/ui/font/bitwig_icons.hpp     (character mappings)"
echo "  src/ui/font/data/${FONT_NAME}.hpp    (extern declarations)"
echo "  src/ui/font/data/${FONT_NAME}.c.inc  (binary data)"
echo ""
echo "Usage:"
echo "  #include \"ui/font/bitwig_icons.hpp\""
echo "  lv_label_set_text(label, BitwigIcon::PLAY);"
